os: linux
dist: xenial
language: python
python:
  - '3.7'
matrix:
  include:
  - env: TOXENV=linting,formatting,typing,canary,coalmine
  fast_finish: true
install:
- pip install -cconstraints.txt -rrequirements/install_requires.txt
- pip install --no-deps -e .
script:
- tox
cache:
- pip
branches:
  only:
  - /^.*master$/
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
  on:
    python: '3.7'
    env: TOXENV=linting,formatting,typing,canary,coalmine
    tags: true
  provider: pypi
  user: "sprigmaintainer"
  password:
    secure: "HEalbwkKnQzeHOLWzN1VgfOjkpnX1egbShFHozzwBUWpt1Ic6M7B4lXG82D5cUZ+iM2KUMSq05hoqNmcojdGIoEo/9mlgjJVuJknVVCB12b918Z4G42egT4XGzsTSXdJZJ5J/AQmdEPXToxEgj6dFYrAD5X3y5RdGCkzPXOClRWxdzJZuFxPl+RKipIrkYvEjeW/RyhKyNGGDRpfTC8p5TzoEuK43Ge4HfafZY8Q48XYrKdP7tdC0WJJK/Iul9TWPyzRECDRFj8/BauV5KraLWaUv7KA4YfwK/80zster+AnM9EZfVHEYNIabeesy86YdzHSscQfnp+UnbyuHFg+suiBNqk2SprXO1wQNM8IvKAl7jCEMdgA+hnkQp3Icmg08hfjaf0/fXIYYvnKnSDd0IBetLAB0Ww2z4yVCEZXcBlDoA4Q6Kq20dKNa/Ey6aU/+dYWpe1iZm2WzeDbux3mWGUUz82UJCCVeJDfOQVcNttpiJGLc+vHWAdb9jKNX2stjNCQwWu6JZsxZgLWVVpLVFnr73u+TIgGL9Lye0hyKVb9d2eJEMEvwKOt8IZD6H5o4TTxwm9h0NsypiezmgAMrnrG4LWFdPHfOJFqXKU0Tfz1jiV8+ToO+zDCCMUMPlRAuaG1V9WJjRyIp9NfA6kivS33SGh2rlswR10rvv+I8LQ="
